In [2]:
import pandas as pd
import numpy as np

In [4]:
X_train = pd.read_csv('max72k_X_train.csv')
X_test = pd.read_csv('max72k_X_test.csv')
y_train = pd.read_csv('max72k_y_train.csv')
y_test = pd.read_csv('max72k_y_test.csv')

In [5]:
X_train.head()

Unnamed: 0  positive_words  negative_words  length  word_count  male_words  \
0      170363               8              12    1516         286           0   
1      129380               0               1      65          12           0   
2       50679               0               0      25           3           0   
3      166490               1               0     101          19           0   
4       83020               0               0      21           5           0   

   female_words  afinn  intensity  positivity  
0             0    1.0   0.069930   -0.013986  
1             0    2.0   0.083333   -0.083333  
2             0    0.0   0.000000    0.000000  
3             0   -2.0   0.052632    0.052632  
4             0    0.0   0.000000    0.000000

In [6]:
X_train

Unnamed: 0  positive_words  negative_words  length  word_count  \
0           170363               8              12    1516         286   
1           129380               0               1      65          12   
2            50679               0               0      25           3   
3           166490               1               0     101          19   
4            83020               0               0      21           5   
...            ...             ...             ...     ...         ...   
136867       90705               0               2      91          17   
136868      145513               0               1      17           2   
136869       70075               0               1      84          16   
136870       86506               0               0      42           7   
136871       40447               0               0      34           7   

        male_words  female_words  afinn  intensity  positivity  
0                0             0    1.0   0.069930   -0.013986  
1                0             0    2.0   0.083333   -0.083333  
2                0             0    0.0   0.000000    0.000000  
3                0             0   -2.0   0.052632    0.052632  
4                0             0    0.0   0.000000    0.000000  
...            ...           ...    ...        ...         ...  
136867           0             0   -7.0   0.117647   -0.117647  
136868           0             0    0.0   0.500000   -0.500000  
136869           0             0   -4.0   0.062500   -0.062500  
136870           0             0    0.0   0.000000    0.000000  
136871           0             0   -1.0   0.000000    0.000000  

[136872 rows x 10 columns]

In [7]:
X_test


Unnamed: 0  positive_words  negative_words  length  word_count  \
0           90391               1               0      43           7   
1          149903               0               0      59          11   
2          161451               5               0      93          17   
3          120108               0               0      55          12   
4           79069               1               0     107          17   
...           ...             ...             ...     ...         ...   
34214       12231               2               0     107          25   
34215       93272               0               0      60          13   
34216      158391               0               0      15           3   
34217      101551               1               0      40           7   
34218      147997               0               0      65          13   

       male_words  female_words  afinn  intensity  positivity  
0               0             0    3.0   0.142857    0.142857  
1               1             0    3.0   0.000000    0.000000  
2               0             0   10.0   0.294118    0.294118  
3               0             0    0.0   0.000000    0.000000  
4               0             0    0.0   0.058824    0.058824  
...           ...           ...    ...        ...         ...  
34214           0             6    1.0   0.080000    0.080000  
34215           0             0    0.0   0.000000    0.000000  
34216           0             0    3.0   0.000000    0.000000  
34217           0             0    3.0   0.142857    0.142857  
34218           0             0    0.0   0.000000    0.000000  

[34219 rows x 10 columns]

In [8]:
y_train

Unnamed: 0   platform
0           170363    youtube
1           129380     reddit
2            50679    twitter
3           166490    youtube
4            83020  instagram
...            ...        ...
136867       90705     reddit
136868      145513     reddit
136869       70075    twitter
136870       86506  instagram
136871       40447    twitter

[136872 rows x 2 columns]

In [9]:
y_test

Unnamed: 0  positive_words  negative_words  length  word_count  \
0           90391               1               0      43           7   
1          149903               0               0      59          11   
2          161451               5               0      93          17   
3          120108               0               0      55          12   
4           79069               1               0     107          17   
...           ...             ...             ...     ...         ...   
34214       12231               2               0     107          25   
34215       93272               0               0      60          13   
34216      158391               0               0      15           3   
34217      101551               1               0      40           7   
34218      147997               0               0      65          13   

       male_words  female_words  afinn  intensity  positivity  
0               0             0    3.0   0.142857    0.142857  
1               1             0    3.0   0.000000    0.000000  
2               0             0   10.0   0.294118    0.294118  
3               0             0    0.0   0.000000    0.000000  
4               0             0    0.0   0.058824    0.058824  
...           ...           ...    ...        ...         ...  
34214           0             6    1.0   0.080000    0.080000  
34215           0             0    0.0   0.000000    0.000000  
34216           0             0    3.0   0.000000    0.000000  
34217           0             0    3.0   0.142857    0.142857  
34218           0             0    0.0   0.000000    0.000000  

[34219 rows x 10 columns]

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
model = DecisionTreeClassifier(max_depth = 10, random_state = 42)

In [12]:
model.fit(X_train, y_train)

ValueError: Input X contains NaN.
DecisionTreeClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Let's get rid of NaN terms

In [13]:
df = pd.read_csv('max72kpost_data.csv')

In [14]:
df

Unnamed: 0                                               text  \
0                0            Had a good first days WE at the herald    
1                1                  whaat. making sure.. she's safe.    
2                2                          HAHAHAHAHAHA, Se ferrou!    
3                3           Cant sleep with bad thoughts in my mind    
4                4  so tired and sick of trains, tho getting on an...   
...            ...                                                ...   
171086      587253                               Best contestant ever   
171087      587254                                       9:16 is gold   
171088      587255  Wait, did she said her cat came back from the ...   
171089      587256  Ok we all have to admit it. Aubrey turns us on...   
171090      587257  She is so boring. If she was my my girlfriend ...   

       platform  positive_words  negative_words  length  word_count  \
0       twitter               1               0      39           9   
1       twitter               0               0      34           5   
2       twitter               0               0      26           3   
3       twitter               0               1      40           8   
4       twitter               0               2      57          11   
...         ...             ...             ...     ...         ...   
171086  youtube               1               0      20           3   
171087  youtube               1               0      12           3   
171088  youtube               0               0     105          19   
171089  youtube               0               0      93          20   
171090  youtube               0               0      61          13   

        male_words  female_words  afinn  intensity  positivity  
0                0             0    3.0   0.111111    0.111111  
1                0             0    1.0   0.000000    0.000000  
2                0             0    0.0   0.000000    0.000000  
3                0             0   -3.0   0.125000   -0.125000  
4                0             0   -4.0   0.181818   -0.181818  
...            ...           ...    ...        ...         ...  
171086           0             0    3.0   0.333333    0.333333  
171087           0             0    2.0   0.333333    0.333333  
171088           0             2   -2.0   0.000000    0.000000  
171089           0             2    4.0   0.000000    0.000000  
171090           0             6   -4.0   0.000000    0.000000  

[171091 rows x 12 columns]

In [15]:
df.dropna()

Unnamed: 0                                               text  \
0                0            Had a good first days WE at the herald    
1                1                  whaat. making sure.. she's safe.    
2                2                          HAHAHAHAHAHA, Se ferrou!    
3                3           Cant sleep with bad thoughts in my mind    
4                4  so tired and sick of trains, tho getting on an...   
...            ...                                                ...   
171086      587253                               Best contestant ever   
171087      587254                                       9:16 is gold   
171088      587255  Wait, did she said her cat came back from the ...   
171089      587256  Ok we all have to admit it. Aubrey turns us on...   
171090      587257  She is so boring. If she was my my girlfriend ...   

       platform  positive_words  negative_words  length  word_count  \
0       twitter               1               0      39           9   
1       twitter               0               0      34           5   
2       twitter               0               0      26           3   
3       twitter               0               1      40           8   
4       twitter               0               2      57          11   
...         ...             ...             ...     ...         ...   
171086  youtube               1               0      20           3   
171087  youtube               1               0      12           3   
171088  youtube               0               0     105          19   
171089  youtube               0               0      93          20   
171090  youtube               0               0      61          13   

        male_words  female_words  afinn  intensity  positivity  
0                0             0    3.0   0.111111    0.111111  
1                0             0    1.0   0.000000    0.000000  
2                0             0    0.0   0.000000    0.000000  
3                0             0   -3.0   0.125000   -0.125000  
4                0             0   -4.0   0.181818   -0.181818  
...            ...           ...    ...        ...         ...  
171086           0             0    3.0   0.333333    0.333333  
171087           0             0    2.0   0.333333    0.333333  
171088           0             2   -2.0   0.000000    0.000000  
171089           0             2    4.0   0.000000    0.000000  
171090           0             6   -4.0   0.000000    0.000000  

[170481 rows x 12 columns]

In [16]:
df

Unnamed: 0                                               text  \
0                0            Had a good first days WE at the herald    
1                1                  whaat. making sure.. she's safe.    
2                2                          HAHAHAHAHAHA, Se ferrou!    
3                3           Cant sleep with bad thoughts in my mind    
4                4  so tired and sick of trains, tho getting on an...   
...            ...                                                ...   
171086      587253                               Best contestant ever   
171087      587254                                       9:16 is gold   
171088      587255  Wait, did she said her cat came back from the ...   
171089      587256  Ok we all have to admit it. Aubrey turns us on...   
171090      587257  She is so boring. If she was my my girlfriend ...   

       platform  positive_words  negative_words  length  word_count  \
0       twitter               1               0      39           9   
1       twitter               0               0      34           5   
2       twitter               0               0      26           3   
3       twitter               0               1      40           8   
4       twitter               0               2      57          11   
...         ...             ...             ...     ...         ...   
171086  youtube               1               0      20           3   
171087  youtube               1               0      12           3   
171088  youtube               0               0     105          19   
171089  youtube               0               0      93          20   
171090  youtube               0               0      61          13   

        male_words  female_words  afinn  intensity  positivity  
0                0             0    3.0   0.111111    0.111111  
1                0             0    1.0   0.000000    0.000000  
2                0             0    0.0   0.000000    0.000000  
3                0             0   -3.0   0.125000   -0.125000  
4                0             0   -4.0   0.181818   -0.181818  
...            ...           ...    ...        ...         ...  
171086           0             0    3.0   0.333333    0.333333  
171087           0             0    2.0   0.333333    0.333333  
171088           0             2   -2.0   0.000000    0.000000  
171089           0             2    4.0   0.000000    0.000000  
171090           0             6   -4.0   0.000000    0.000000  

[171091 rows x 12 columns]

In [18]:
df = df.dropna()

In [19]:
df

Unnamed: 0                                               text  \
0                0            Had a good first days WE at the herald    
1                1                  whaat. making sure.. she's safe.    
2                2                          HAHAHAHAHAHA, Se ferrou!    
3                3           Cant sleep with bad thoughts in my mind    
4                4  so tired and sick of trains, tho getting on an...   
...            ...                                                ...   
171086      587253                               Best contestant ever   
171087      587254                                       9:16 is gold   
171088      587255  Wait, did she said her cat came back from the ...   
171089      587256  Ok we all have to admit it. Aubrey turns us on...   
171090      587257  She is so boring. If she was my my girlfriend ...   

       platform  positive_words  negative_words  length  word_count  \
0       twitter               1               0      39           9   
1       twitter               0               0      34           5   
2       twitter               0               0      26           3   
3       twitter               0               1      40           8   
4       twitter               0               2      57          11   
...         ...             ...             ...     ...         ...   
171086  youtube               1               0      20           3   
171087  youtube               1               0      12           3   
171088  youtube               0               0     105          19   
171089  youtube               0               0      93          20   
171090  youtube               0               0      61          13   

        male_words  female_words  afinn  intensity  positivity  
0                0             0    3.0   0.111111    0.111111  
1                0             0    1.0   0.000000    0.000000  
2                0             0    0.0   0.000000    0.000000  
3                0             0   -3.0   0.125000   -0.125000  
4                0             0   -4.0   0.181818   -0.181818  
...            ...           ...    ...        ...         ...  
171086           0             0    3.0   0.333333    0.333333  
171087           0             0    2.0   0.333333    0.333333  
171088           0             2   -2.0   0.000000    0.000000  
171089           0             2    4.0   0.000000    0.000000  
171090           0             6   -4.0   0.000000    0.000000  

[170481 rows x 12 columns]

In [20]:
y = df['platform']

In [21]:
X = df[['positive_words', 'negative_words', 'length', 'word_count', 'male_words', 'female_words', 'afinn', 'intensity', 'positivity']]

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y, random_state=42, test_size=0.2)

In [24]:
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, random_state=42)

In [25]:
y_pred = model.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix


In [27]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  207  2302   411    89]
 [   55 12346  1992    34]
 [   51  7821  6508    20]
 [  103  1493   439   226]]
              precision    recall  f1-score   support

   instagram       0.50      0.07      0.12      3009
      reddit       0.52      0.86      0.64     14427
     twitter       0.70      0.45      0.55     14400
     youtube       0.61      0.10      0.17      2261

    accuracy                           0.57     34097
   macro avg       0.58      0.37      0.37     34097
weighted avg       0.60      0.57      0.53     34097



In [28]:
model2 = DecisionTreeClassifier(max_depth = 3, random_state = 42)

In [29]:
model2.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [31]:
y_pred2 = model2.predict(X_test)

In [32]:
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[  137  2485   295    92]
 [    8 12498  1892    29]
 [    2  8365  6026     7]
 [   86  1573   390   212]]
              precision    recall  f1-score   support

   instagram       0.59      0.05      0.08      3009
      reddit       0.50      0.87      0.64     14427
     twitter       0.70      0.42      0.52     14400
     youtube       0.62      0.09      0.16      2261

    accuracy                           0.55     34097
   macro avg       0.60      0.36      0.35     34097
weighted avg       0.60      0.55      0.51     34097



In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [36]:
y_pred_rf = rf.predict(X_test)

In [37]:
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[  321  1961   622   105]
 [  316 10125  3816   170]
 [  250  6281  7658   211]
 [  133  1242   623   263]]
              precision    recall  f1-score   support

   instagram       0.31      0.11      0.16      3009
      reddit       0.52      0.70      0.59     14427
     twitter       0.60      0.53      0.56     14400
     youtube       0.35      0.12      0.17      2261

    accuracy                           0.54     34097
   macro avg       0.45      0.36      0.37     34097
weighted avg       0.52      0.54      0.52     34097

